name: JMeter Performance Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzvf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/jmeter

      - name: Criar pasta de relatórios
        run: mkdir -p ./reports/html

      - name: Executar teste JMeter
        run: |
          /opt/jmeter/bin/jmeter -n \
            -t ./testes/stress-test.jmx \
            -l ./reports/resultados.jtl \
            -e -o ./reports/html

      - name: Upload dos relatórios HTML
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: ./reports/html
